# Generated by Django 6.0.3 on 2026-04-06 17:11

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _wipe_core_and_legacy_auth_tables(apps, schema_editor):
    """
    Vacía el esquema previo de `core` y tablas `auth_user*` legacy antes de recrear modelos.
    Útil al reemplazar migraciones o al pasar de auth.User a core.User.
    """
    connection = schema_editor.connection
    vendor = connection.vendor
    with connection.cursor() as cursor:
        existing = set(connection.introspection.table_names(cursor))

    legacy = frozenset({
        'auth_user',
        'auth_user_groups',
        'auth_user_user_permissions',
    })
    to_drop = sorted(
        t for t in existing
        if t.startswith('core_') or t in legacy
    )
    if not to_drop:
        return

    if vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute('PRAGMA foreign_keys = OFF')
            for table in to_drop:
                cursor.execute(f'DROP TABLE IF EXISTS "{table}"')
            cursor.execute('PRAGMA foreign_keys = ON')
    elif vendor == 'postgresql':
        with connection.cursor() as cursor:
            for table in to_drop:
                cursor.execute(
                    'DROP TABLE IF EXISTS %s CASCADE' % connection.ops.quote_name(table)
                )
    else:
        with connection.cursor() as cursor:
            for table in to_drop:
                cursor.execute(
                    'DROP TABLE IF EXISTS %s' % connection.ops.quote_name(table)
                )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(_wipe_core_and_legacy_auth_tables, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'proveedor de autenticación',
                'verbose_name_plural': 'proveedores de autenticación',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cuenta de facturación',
                'verbose_name_plural': 'cuentas de facturación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('max_empresas', models.PositiveIntegerField(blank=True, help_text='Máximo de empresas por cuenta de facturación. Vacío = sin límite.', null=True)),
                ('max_organizaciones', models.PositiveIntegerField(blank=True, help_text='Máximo de organizaciones por empresa. Vacío = sin límite.', null=True)),
                ('max_sucursales', models.PositiveIntegerField(blank=True, help_text='Máximo de sucursales por empresa (todas las orgs). Vacío = sin límite.', null=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'estado de suscripción',
                'verbose_name_plural': 'estados de suscripción',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_user',
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='core.billingaccount')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to='core.empresa')),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('second_last_name', models.CharField(blank=True, max_length=100)),
                ('personal_email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='PersonEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.empresa')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_memberships', to='core.person')),
            ],
            options={
                'verbose_name': 'membresía persona-empresa',
                'verbose_name_plural': 'membresías persona-empresa',
            },
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='core.module')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='core.plan')),
            ],
            options={
                'verbose_name': 'módulo del plan',
                'verbose_name_plural': 'módulos del plan',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.ManyToManyField(related_name='plans', through='core.PlanModule', to='core.module'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('modules', models.ManyToManyField(blank=True, related_name='roles', to='core.module')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.billingaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.plan')),
                ('status', models.ForeignKey(default=core.models._default_subscription_status_trialing_pk, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionstatus')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.organizacion')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.empresa')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.organizacion')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.role')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'asignación de rol',
                'verbose_name_plural': 'asignaciones de rol',
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_uid', models.CharField(blank=True, help_text='ID único en el proveedor (vacío para password local).', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_identities', to='core.authprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'identidad de usuario',
                'verbose_name_plural': 'identidades de usuario',
                'ordering': ['-is_primary', 'provider__sort_order', 'provider__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('billing_account', 'slug'), name='uniq_empresa_slug_per_account'),
        ),
        migrations.AddConstraint(
            model_name='personempresa',
            constraint=models.UniqueConstraint(fields=('person', 'empresa'), name='uniq_person_empresa'),
        ),
        migrations.AddConstraint(
            model_name='planmodule',
            constraint=models.UniqueConstraint(fields=('plan', 'module'), name='uniq_plan_module'),
        ),
        migrations.AddConstraint(
            model_name='personroleassignment',
            constraint=models.UniqueConstraint(fields=('person', 'role', 'empresa', 'organizacion', 'sucursal'), name='uniq_person_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='useridentity',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'provider_uid'), name='uniq_user_provider_uid'),
        ),
    ]
