# Generated by Django 6.0.3 on 2026-04-06 21:04

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_campos_ingles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentafacturacion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'cuenta de facturación', 'verbose_name_plural': 'cuentas de facturación'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='estadosuscripcion',
            options={'ordering': ['orden', 'codigo'], 'verbose_name': 'estado de suscripción', 'verbose_name_plural': 'estados de suscripción'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='organizacion',
            options={'ordering': ['nombre'], 'verbose_name': 'organización', 'verbose_name_plural': 'organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['orden_presentacion', 'codigo'], 'verbose_name': 'plan', 'verbose_name_plural': 'planes'},
        ),
        migrations.AlterModelOptions(
            name='rolempresa',
            options={'ordering': ['codigo'], 'verbose_name': 'rol por empresa', 'verbose_name_plural': 'roles por empresa'},
        ),
        migrations.AlterModelOptions(
            name='rolpersonaempresa',
            options={'verbose_name': 'asignación rol persona-empresa', 'verbose_name_plural': 'asignaciones rol persona-empresa'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'suscripción', 'verbose_name_plural': 'suscripciones'},
        ),
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icono',
            field=models.CharField(blank=True, default='', help_text='Clave del icono en la UI (p. ej. Lucide en PascalCase).', max_length=64),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='personaempresa',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_empresa', to='core.persona'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='modulos',
            field=models.ManyToManyField(related_name='planes', through='core.PlanModulo', to='core.modulo'),
        ),
        migrations.AlterField(
            model_name='planmodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modulos', to='core.modulo'),
        ),
        migrations.AlterField(
            model_name='planmodulo',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modulos', to='core.plan'),
        ),
        migrations.AlterField(
            model_name='rolempresa',
            name='modulos',
            field=models.ManyToManyField(blank=True, related_name='roles_empresa', to='core.modulo'),
        ),
        migrations.AlterField(
            model_name='rolpersonaempresa',
            name='membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='core.personaempresa'),
        ),
        migrations.AlterField(
            model_name='rolpersonaempresa',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='core.organizacion'),
        ),
        migrations.AlterField(
            model_name='rolpersonaempresa',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.rolempresa'),
        ),
        migrations.AlterField(
            model_name='rolpersonaempresa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='cuenta_facturacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='core.cuentafacturacion'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.ForeignKey(default=core.models._pk_estado_suscripcion_trialing, on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='core.estadosuscripcion'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='core.plan'),
        ),
    ]
